enum AreaTypes {
  STREAMER_AREA_TYPE_CIRCLE,
  STREAMER_AREA_TYPE_CYLINDER,
  STREAMER_AREA_TYPE_SPHERE,
  STREAMER_AREA_TYPE_RECTANGLE,
  STREAMER_AREA_TYPE_CUBOID,
  STREAMER_AREA_TYPE_POLYGON,
}
export default AreaTypes;
