enum ItemTypes {
  STREAMER_TYPE_OBJECT,
  STREAMER_TYPE_PICKUP,
  STREAMER_TYPE_CP,
  STREAMER_TYPE_RACE_CP,
  STREAMER_TYPE_MAP_ICON,
  STREAMER_TYPE_3D_TEXT_LABEL,
  STREAMER_TYPE_AREA,
  STREAMER_TYPE_ACTOR,
}
export default ItemTypes;
